# These are supported funding model platforms
ko_fi: balansse
liberapay: balansse
custom: ['https://www.buymeacoffee.com/balansse'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
